### ISSUE TITLE
能不能开发一个置顶功能？

### ISSUE THREAD

**Issue by hanxiatu-fc** [gzdaijie/koa-react-server-render-blog#71]

**Comment by geektutu** [comment]
![image](https://user-images.githubusercontent.com/13294018/61396826-26a33a80-a8fb-11e9-9d83-c9c96f0d1039.png)

需要置顶的文章中添加`top`属性即可，代表置顶顺序。1，2，3，4 ...，建议不超过3篇。

https://geektutu.com 查看效果。

```yml
tags:
- Python
categories:
- TensorFlow入门
top: 2
image: post/tensorflow2-gym-nn/cartpole_v0_failed.gif
```
