### ISSUE TITLE
无法正确显示有序列表

### ISSUE THREAD

**Issue by bbruceyuan** [gzdaijie/koa-react-server-render-blog#84]
我发现使用这个主题没有办法正确显示有序列表。

我使用以下 markdown 语法：
```
1. paper name1
2. paper name2
```
具体的错误显示如 [https://bbruceyuan.github.io/post/7.html](https://bbruceyuan.github.io/post/7.html) 显示，只要是有序的列表，就会被显示成 小圆圈。

**Comment by geektutu** [comment]
source/css/markdown.css 中去掉

```css
.markdown-it ol {
  list-style-type: circle;
}
```

感谢指出问题，已经解决。
